version: "3"

services:
    fer_model:
        build: .
        volumes:
            - ./app/:/fer_model/app/
            - ./images/:/fer_model/images/
        ports:
            - 5000:5000
        command: bash -c "./.venv/bin/python3.8 ./app/main.py"
